Feature/team page redesign adjust font
speer-source/speer-technologies.github.io pull request #119
Opened 2022-03-08 21:27 UTC by cding-at-speer

2022-03-08 21:33 UTC, cding-at-speer commented
now it can be merged : ) @konner-at-speer

2022-03-08 21:57 UTC, konner-at-speer requested changes
Changing the `h1`, `h2` tags can be a workaround for this font-weight issue, but what happens if the style sheets fail to load? These special elements not only provide us with a fallback but are also important for accessibility and SEO.

I'd suggest reverting your recent changes and overwriting the default `font-weight` by simply adding `font-weight: normal;` to the **Title** and **SubTitle** styled components..

2022-03-08 22:19 UTC, cding-at-speer commented
@konner-at-speer I put the h2 tags back and added the font-weight property for it. for h1, I think it is fine to just leave it as it is bold anyway (if you agree, you can just merge it in :)

2022-03-09 00:03 UTC, konner-at-speer approved these changes

2022-03-09 00:03 UTC, merged