Feature/replace blog photo
speer-source/speer-technologies.github.io pull request #126
Opened 2022-03-16 02:40 UTC by ablazys

After replacing the blog photos, I ran into the issue that the carousel was not displaying the proper images according to the design. After searching for a while, I found that the carousel was pulling from the "popular" section with the attributes in` useblogposts.tsx` . To remedy this, I created a new attribute called carousel and set it to "true". I then changed hero.tsx to pull carousel slides from carousel.map instead of `popular.map`.  This allowed me to add the new attribute in blogPosts.json to specify which posts I wanted to show in the carousel.

2022-03-16 20:32 UTC, konner-at-speer commented on src/view/pages/Blog/hooks/blogPosts.json
> +        "carousel": "true",
Booleans are [valid JSON types](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON). Therefore, `"true"` can be replaced with `true`.

2022-03-16 20:33 UTC, konner-at-speer commented on src/view/pages/Blog/hooks/blogPosts.json
> +        "carousel":"true",
Booleans are [valid JSON types](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON). Therefore, "true" can be replaced with true.

2022-03-16 20:35 UTC, konner-at-speer commented on src/view/pages/Blog/hooks/useBlogPosts.tsx
> +    carousel  : string;
Shouldn't this `carousel` key/value be optional since it is not required on every Post?

2022-03-18 12:19 UTC, konner-at-speer requested changes
Looks good! Just one additional small change: Could you revert how the colons were structured for all `types` and `interfaces` across all your changes for this PR?  

<img width="674" alt="colon_convention_change" src="https://user-images.githubusercontent.com/73895454/159001323-0182d5c3-3e68-40b2-864e-00614173b0c1.png">

2022-03-18 12:19 UTC, konner-at-speer commented on src/view/pages/Blog/hooks/useBlogPosts.tsx
> +    carousel?: boolean;
The colons(`:`) used here were intentionally structured vertically for readability. Can you revert these changes to how they were implemented before?

2022-03-18 14:21 UTC, ablazys commented on src/view/pages/Blog/hooks/useBlogPosts.tsx
> +    carousel?: boolean;
Oh strange, I wonder how that changed so drastically? Perhaps because of the linter? Not sure. Will fix right now

2022-03-24 15:06 UTC, konner-at-speer requested changes

2022-03-24 15:06 UTC, konner-at-speer commented on src/view/pages/Blog/components/BlogTile.tsx
> +        window.scrollTo(0,0);
Perfect. Is there an option for scroll behaviour here?

2022-03-25 18:11 UTC, konner-at-speer approved these changes

2022-03-25 18:12 UTC, merged