Feature/team page about section
speer-source/speer-technologies.github.io pull request #127
Opened 2022-03-18 14:01 UTC by sbounadja-at-speer

2022-03-21 18:57 UTC, konner-at-speer requested changes
Overall, looks good! Make sure you double-check the margins and font sizes for all the elements. Also, I noticed the 'Speer' image ( **S** specifically) seems cut off a bit. Can you investigate this? May have to take this up with design.
![Screen Shot 2022-03-21 at 2 54 38 PM](https://user-images.githubusercontent.com/73895454/159344366-6641ed4a-ba04-498a-81b3-50be9032c0d5.png)

2022-03-21 18:57 UTC, konner-at-speer commented on src/view/pages/Team/sections/About.tsx
> +    }
For tablet screens and larger, let's add `padding-left: 25px` to add additional space.

2022-03-21 18:57 UTC, konner-at-speer commented on src/view/pages/Team/sections/About.tsx
>  const Content = styled.p`
Double-check font-size and margins here

2022-03-22 01:36 UTC, sbounadja-at-speer commented on src/view/pages/Team/sections/About.tsx
> +const Button = styled.a`
has been replaced with button element.

2022-03-22 01:36 UTC, sbounadja-at-speer commented on src/view/pages/Team/sections/About.tsx
> +    background-color: ${Palette.BLACK};
has been replaced with {Palette.DARK_GRAY}

2022-03-22 01:36 UTC, sbounadja-at-speer commented on src/view/pages/Team/sections/About.tsx
> +    height:100%;
formatting fixed.

2022-03-22 01:37 UTC, sbounadja-at-speer commented on src/view/pages/Team/sections/About.tsx
> +const SpeeImage = styled.img<{ src: string }>`
naming fixed.

2022-03-22 01:37 UTC, sbounadja-at-speer commented on src/view/pages/Team/sections/About.tsx
> +        margin-bottom: 25px;
values has been replaced with proper onces.

2022-03-22 01:38 UTC, sbounadja-at-speer commented on src/view/pages/Team/sections/About.tsx
>  const Content = styled.p`
margin fixed

2022-03-22 01:39 UTC, sbounadja-at-speer commented on src/view/pages/Team/sections/About.tsx
> +    }
added some margin there.

2022-03-22 12:06 UTC, konner-at-speer requested changes
Just a few additional changes. Also, do we need those **about_us** PNG/WEBP assets anymore if we're using svg?

2022-03-22 12:06 UTC, konner-at-speer commented on src/view/pages/Team/sections/About.tsx
> +        font-family: 'Poppins-Medium';
The font here is too bold. I'd suggest you revert this change back to `font-family: 'Poppins-Regular';` for all screen sizes.

2022-03-22 14:22 UTC, sbounadja-at-speer commented on src/view/pages/Team/sections/About.tsx
> +        font-family: 'Poppins-Medium';
done.

2022-03-22 14:23 UTC, sbounadja-at-speer commented
> Just a few additional changes. Also, do we need those **about_us** PNG/WEBP assets anymore if we're using SVG's?

we have to remove the related object from `imagesWithAdditionalFormats` to be able to delete those files.

2022-03-22 14:45 UTC, sbounadja-at-speer commented
> > Just a few additional changes. Also, do we need those **about_us** PNG/WEBP assets anymore if we're using SVG's?
> > > we have to remove the related object from `imagesWithAdditionalFormats` to be able to delete those files.
> 
> Can we remove the related object from `imagesWithAdditionalFormats`?

assets has been removed.

2022-03-22 16:28 UTC, merged