Fix/team page hero Btn dimensions change
speer-source/speer-technologies.github.io pull request #128
Opened 2022-03-18 21:08 UTC by sbounadja-at-speer

2022-03-21 20:16 UTC, konner-at-speer requested changes
A few quick changes: Double-check margins and remove the south arrow asset and use the south arrow HTML symbol instead( see comments below )

2022-03-21 20:16 UTC, konner-at-speer commented on src/view/pages/Team/sections/Hero.tsx
> +                        <ScrollIcon icon={IMAGES.downArrowIcon}></ScrollIcon>
Remove this since we'll be using the default south arrow symbol. Revert assets added as well.

2022-03-21 20:16 UTC, konner-at-speer commented on src/view/pages/Team/sections/Hero.tsx
> +                        <ScrollButtonText textColor={Palette.DARK_GRAY}>Learn About Us</ScrollButtonText>
We can actually use a south arrow symbol instead of an icon asset. [Examples of symbols we can use](https://www.toptal.com/designers/htmlarrows/arrows/)

We can implement this south arrow using a :`after` pseudo-class:

&:after {
        font-family: 'Poppins-Regular';
        content: '\\2193';
        color: ${({ textColor })=>textColor};

 };

2022-03-22 12:23 UTC, konner-at-speer requested changes
Just a few minor adjustments.

2022-03-22 12:23 UTC, konner-at-speer commented on src/view/pages/Team/sections/Hero.tsx
>      font-family: 'Poppins-Light';
Looks like we use `font-family: 'Poppins-Regular';` for mobile screens and `font-family: 'Poppins-Light';` for tablet screens and larger. Also, let's add a `line-height: 104px;` for tablet screens and larger as well.

2022-03-22 12:23 UTC, konner-at-speer commented on src/view/pages/Team/sections/Hero.tsx
> +        bottom: 2.5px;
The south arrows seems elevated too much. Do we need to use `bottom: 2.5px;`? 
See image below:
<img width="697" alt="Screen Shot 2022-03-22 at 8 10 33 AM" src="https://user-images.githubusercontent.com/73895454/159481142-243a6bbe-2911-4758-b96e-028e7e1abf04.png">

2022-03-22 14:29 UTC, sbounadja-at-speer commented on src/view/pages/Team/sections/Hero.tsx
> +        bottom: 2.5px;
Thats wierd!!. looks fine in chrome and Edge.

2022-03-22 14:29 UTC, sbounadja-at-speer commented on src/view/pages/Team/sections/Hero.tsx
>      font-family: 'Poppins-Light';
done.

2022-03-22 16:36 UTC, merged