Feature/dealer methods
speer-source/speer-technologies.github.io pull request #138
Opened 2022-04-05 21:31 UTC by ablazys

2022-04-06 14:51 UTC, konner-at-speer requested changes
Great work! But I do have some questions/suggestions:

1. Let's use the large SVG image formats for the **FLEET**, **INNOVATIVE**, and **SYSTEM** images? They can be found [here](https://app.zeplin.io/project/620eb66aaf161da95434c820/screen/62430cc2584b50084902ae29).
2. I'm pondering if it'd be best if we're to use SVG's for the maps as well? If you compare the images to the team page **About Us** and **Our Values** sections, they are much sharper / less pixelated. 
3. Responsiveness doesn't seem to be working for tablet screens across all case studies. We may need to create a ticket for this issue and coordinate with design. See image attached 
4. "**Dealer-Method**s" is suppose to be changed to "**Fleet Management Software**"? See image attached 

<img width="442" alt="dealer-methods_issue" src="https://user-images.githubusercontent.com/73895454/161996826-ca0f902d-1db6-4bef-b391-fe7069f4a50f.png">
<img width="1504" alt="tablet_responsiveness" src="https://user-images.githubusercontent.com/73895454/161996841-64f003fe-9b6a-4504-8fd5-4e70c1f8fd6d.png">

2022-04-06 14:51 UTC, konner-at-speer commented on src/view/pages/NewCaseStudy/sections/Results.tsx
> +  font-size: 80px;
This is the correct font for Dealer-Methods but is correct for Poppy case-study?

2022-04-06 14:51 UTC, konner-at-speer commented on src/view/pages/NewCaseStudy/sections/Results.tsx
> +const StatBody = styled.div<{statsType?: number;}>`
Are we even using `statsType `here?

2022-04-06 14:51 UTC, konner-at-speer commented on src/view/pages/NewCaseStudy/sections/Results.tsx
> +    margin-right: ${(props) => (props.statsType === 1? '0' : '200px')};
Is this change necessary? If so, it seems like this change is introducing breaking changes to the Poppy Case study page

2022-04-06 14:51 UTC, konner-at-speer commented on src/view/pages/NewCaseStudy/sections/Results.tsx
> +    margin-right: ${(props) => (props.statsType === 1? '0' : '200px')};
This may be introducing breaking changes to the Poppy Case study page

2022-04-08 16:31 UTC, konner-at-speer requested changes
Great work! There are a few additional changes. 

Double-check that there are no breaking changes introduced on the Poppy page. A simple way to check this is by switching between [speer.io](https://speer.io/work/poppy) and your current work -- you'll see the diffs right away.

https://user-images.githubusercontent.com/73895454/162483894-44bc1c5a-b452-46db-beae-b43a9dca3f69.mov

2022-04-08 16:31 UTC, konner-at-speer commented on src/view/pages/NewCaseStudy/sections/Results.tsx
>      width: 85vw;
Hmm. I think a better solution would be to remove` width: 85vw;` here. Then, adjust the padding for this components parent( `<Container />` ) for tablets screens and larger. Reference how the padding is one other sections within this page or on [zeplin](https://app.zeplin.io/project/620eb66aaf161da95434c820/screen/62430e03f34b071fcfc94af0). See video below

https://user-images.githubusercontent.com/73895454/162482729-9d57a8dd-e73b-471b-bc46-62e9514437cf.mov

2022-04-08 22:11 UTC, ablazys commented on src/view/pages/NewCaseStudy/sections/Results.tsx
> +  font-size: ${(props) => (props.statsType === StatsType.HORIZONTAL? '80px' : '50px')};
This was actually fixing a mistake I made the first time around. The logic now is correct, I double checked with the proper text sizes on Zepplin

2022-04-08 22:15 UTC, ablazys commented on src/view/pages/NewCaseStudy/sections/Results.tsx
> +    margin-left: ${(props) => (props.statsType === StatsType.HORIZONTAL ? '-25px' : '0px')};
Nope! Double checked it right now and compared it to the Zepplin, no issues found!

2022-04-08 22:17 UTC, ablazys commented on src/view/pages/NewCaseStudy/sections/Results.tsx
> +const StatHead = styled.div<{ statsType?: number;}>`
What device is this that's causing it to look like this? Looks great on the iPhone 12 emulator on Dev tools
<img width="535" alt="Screen Shot 2022-04-08 at 6 17 22 PM" src="https://user-images.githubusercontent.com/98362210/162540850-fe33bf7f-4539-4c2a-8658-63cd73995cba.png">

2022-04-12 16:16 UTC, konner-at-speer requested changes

2022-04-12 16:16 UTC, konner-at-speer commented on src/view/pages/NewCaseStudy/sections/Results.tsx
> +  ${(props) => (props.statsType === StatsType.HORIZONTAL ? 'margin-right: 25px' : '')};
Remove `margin-right` entirely, replace `inherit` with `initial` since we want to reset text-align to its default value, and add `width: 100%;` so we align the text center. 

Also, add `text-align: center;` for tablet screens and larger since we can align the StatTitle center for the Poppy case study.

```suggestion
  text-align: ${(props) => (props.statsType === StatsType.HORIZONTAL ? 'center' : 'initial')};
  width: 100%;
  @media ${MediaQuery.tablet} {
    text-align: center;
  };
```

2022-04-13 19:39 UTC, konner-at-speer approved these changes

2022-04-13 19:40 UTC, merged