Implement standard layout for blog posts
speer-source/speer-technologies.github.io pull request #24
Opened 2021-08-05 17:58 UTC by spark-at-speer

2021-08-17 05:11 UTC, rhys-at-speer requested changes
Looking great.

Can you also merge in the develop branch. Also, an you set up an example of the standard layout that I could checkout quickly? Or point me in the right direction if I missed it.

2021-08-17 05:11 UTC, rhys-at-speer commented on src/view/pages/BlogPost/BlogPost.tsx
> +            const { category, title, photo, author, image, layout, posts } = fetchBlogPostData();
Could setup `fetchBlogPostData` to return a promise if you want, to get closer to a mock api

2021-08-17 05:11 UTC, rhys-at-speer commented on src/view/pages/BlogPost/BlogPost.tsx
> +    const getFirstName = (fullName: string | undefined): string =>
Maybe instead we want this fn to accept `HeroData`, and then pull the `author` prop from this object.

2021-08-17 05:11 UTC, rhys-at-speer commented on src/view/pages/BlogPost/components/Post.tsx
> +            }
The default case is unneeded here since the transpiler can determine that this switch statement is exhaustive (it covers all possible cases of the `PostLayout` enum)

2021-08-17 05:11 UTC, rhys-at-speer commented on src/view/pages/BlogPost/components/Socials.tsx
> +    GITHUB   = 'github',
```suggestion
    //GITHUB   = 'github',
```

Then get rid of the default case in the switch statement; better to keep it exhaustive unless we have a good reason to handle a catch-all case

2021-08-17 05:11 UTC, rhys-at-speer commented on src/view/pages/BlogPost/components/Post.tsx
> +    const { question, answer } = data as PostQuestionAndAnswer;
Maybe we want to instead define a `PostData` type that has the above types as properties. Might look a bit cleaner.

2021-08-17 14:29 UTC, spark-at-speer commented on src/view/pages/BlogPost/BlogPost.tsx
> +    `}
Changed to:
```
    ${({ layout }) => 
    {
        switch(layout) 
        {
        case PostLayout.STANDARD:
            return 'margin: 11px 132px 0 132px;';
        case PostLayout.QUESTION_AND_ANSWER:
            return `margin-top: 111px; 
                    text-align: right;`;
        }
    }}
```

2021-08-17 15:52 UTC, spark-at-speer commented on src/view/pages/BlogPost/BlogPost.tsx
> +            const { category, title, photo, author, image, layout, posts } = fetchBlogPostData();
Made it so that only one of the blog posts (popular0) will display the standard format and the rest of the blog posts will display using the question and answer format. This is placeholder code until the back-end is developed so that you can still test either format without having to change the code.

```
    const fetchBlogPostDataById = (id: string): Promise<BlogPostData> => 
    {
        return new Promise<BlogPostData>((resolve, reject) => 
        {
            try
            {
                // blogPosts[0] - standard format
                // blogPosts[1] - question and answer format
                if (id === 'popular0')
                {
                    resolve(blogPosts[0]);
                }
                else
                {
                    resolve(blogPosts[1]);
                }
            }
            catch(err)
            {
                reject(err);
            }
        });
    };
```

2021-08-17 15:57 UTC, spark-at-speer commented on src/view/pages/BlogPost/BlogPost.tsx
> +    const getFirstName = (fullName: string | undefined): string =>
Changed to:

```
    const getFirstName = (heroData?: HeroData): string =>
    {
        return heroData && heroData.author ? heroData.author.split(' ')[0] : '';
    };
```

2021-08-17 17:10 UTC, spark-at-speer commented on src/view/pages/BlogPost/components/Post.tsx
> +    const { question, answer } = data as PostQuestionAndAnswer;
Changed to:

`interface PostData extends PostTitle, PostDescription, PostImage, PostYoutubeEmbed, PostQuestionAndAnswer { }`

2021-08-17 19:20 UTC, spark-at-speer commented
See commit [848f20c](https://github.com/speer-source/speer-technologies.github.io/pull/24/commits/848f20ca8756c76cdbc4bde811be17279fe81743) for the changes. 

Merged from develop and requested changes as per above were made

2021-08-20 04:40 UTC, rhys-at-speer approved these changes

2021-08-20 04:41 UTC, merged